team-soapstone/front-end-capstone

package.json

Add a 'npm start' script to automatically run live-server on our client's html

update packagejson for npm start script

---

client/src/components/App.jsx
client/src/components/Overview/AddToCart.jsx
client/src/components/Overview/ImageGallery.jsx
client/src/components/Overview/Overview.jsx
client/src/components/Overview/ProductDescription.jsx
client/src/components/Overview/ProductInformation.jsx
client/src/components/Overview/Share.jsx
client/src/components/Overview/StyleSelector.jsx

Hey Kevin 👋
Added all component files for overview component.
Imported and added Overview as a rendered component in App.jsx.

Feature overview components

---

client/src/components/App.jsx
client/src/components/QA/AddAnswer.jsx
client/src/components/QA/AddQuestion.jsx
client/src/components/QA/QuestionItem.jsx
client/src/components/QA/QuestionList.jsx
client/src/components/QA/QuestionSearch.jsx
client/src/components/QA/QuestionView.jsx

Hey guys! Just created a folder for my component and populated it with all the files I think I'll need!

built skeleton files for Q/A component

---

__tests__/QuestionView.test.js
client/src/components/QA/QuestionView.jsx

Just getting a feel for Jest - wrote a test to make sure QuestionsView is rendering within App.js on init

implemented initial QuestionsView rendering test

---

.gitignore
babel.config.js
client/src/components/App.jsx
client/src/components/RatingsAndReviews/NewReview.jsx
client/src/components/RatingsAndReviews/ProductBreakdown.jsx
client/src/components/RatingsAndReviews/RatingBreakdown.jsx
client/src/components/RatingsAndReviews/RatingsAndReviews.jsx
client/src/components/RatingsAndReviews/Review.jsx
client/src/components/RatingsAndReviews/ReviewList.jsx

Hey guys,
Put in my components in for my widget. Please review when you guys get the chance. Thanks!

created R&R component and child skeletons

---

client/src/components/App.jsx
client/src/components/QA/QuestionView.jsx

Hey guys! So I passed the current product ID from the state in App.js to QuestionView (the main Q&A component), and then within QuestionView performed an Axios request to get the questions associated with that current product (and then passed those to QuestionsList, where I'll render them).

GETs questions 

---

__tests__/App.test.js
__tests__/setupTests.js
client/src/components/App.jsx
package-lock.json
package.json

Hey guys,
I went down a rabbit hole trying to figure out a good testing for our API calls on my own widget. I ended up going with Enzyme and I did a sample test on the App component since we do two API calls there. As a side note, enzyme is a good testing suite to check Props and State within each component. Could be useful for our future testing.
Also, according to the internet and stack overflow it's bad practice to test implementation within React components (such as setState, or if props is right at a current component). It is better to test the component renders what we want correctly onto the screen. But since App doesn't render anything, I figured it's okay to have this a supplementary test. Let me know what you think. I had to add a few more stuff into package.json such as the …

Enzyme Testing

---

client/src/components/QA/QuestionItem.jsx
client/src/components/QA/QuestionList.jsx
client/src/components/QA/QuestionView.jsx

To be rendered in the QuestionList component, each question (up to 4, but can be expanded with a button I'll implement in a later commit) is rendered alongside 2  of its answers (this number will also eventually be adjustable).

Constructed items for individual product questions 

---

client/dist/styles.css
client/src/components/App.jsx
client/src/components/Ratings.jsx
client/src/components/RatingsAndReviews/NewReview.jsx
client/src/components/RatingsAndReviews/ProductBreakdown.jsx
client/src/components/RatingsAndReviews/RatingBreakdown.jsx
client/src/components/RatingsAndReviews/RatingsAndReviews.jsx
client/src/components/RatingsAndReviews/Review.jsx
client/src/components/RatingsAndReviews/ReviewList.jsx

This PR is for ticket #22 to dynamically render each review within Review List.
- The user wanted the review list to be scrollable, but with a fix height. I edited CSS files to add a scroll bar on the main App, and a hidden scroll bar within reviewList.
- The reviews should display 2 tiles at a time. If more than 2 reviews, a button will appear below to render 2 more. If there are  2 or less reviews, the button will disappear. (Need to write a test for this).
- Each click should render 2 more reviews. Once all reviews are rendered, the button should disappear. (Need to write a test for this).
- The ordering and filter of this list should work. (This is not implemented yet. The sort can be implemented within the Rating and Reviews parent-container as part of the API call to pull sorted …

ks/rr - Review List component - Ticket #22

---

client/src/components/Ratings.jsx
client/src/components/RatingsAndReviews/RatingsAndReviews.jsx
client/src/components/RatingsAndReviews/Review.jsx
client/src/components/RatingsAndReviews/ReviewList.jsx
package-lock.json
package.json
webpack.config.js

This PR is for tickets #24, 25, and 26. They're bundled together as some functionalities are spread across all 3 tickets.
Made the following changes:
- Created a sort dropdown that will invoke a function on the parent component to make another GET request with an additional sort parameter.
- Render each review with proper elements such as rating, date, review, etc. 
- I moved in the moment library for easier date formatting, will need another NPM Install 
- Created a button that will constrain the review list to render only 2 reviews at a time.
- Also refactored some code within parent Ratings and Review, to pull all reviews data based off how many ratings were given on the meta data so better matches how many reviews there actually is.

ks/rr-v3 - Review List and Review components - Ticket # 24, 25, and 26

---

client/dist/styles.css
client/src/components/App.jsx
client/src/components/Overview/ImageGallery.jsx
client/src/components/Overview/Overview.jsx

Hi @kyelindholm @ks10825n, happy new year!
I implemented the default view for the image gallery.
Changed the default value for currentProduct and productRatings on the app.jsx state to empty strings instead of empty objects so they come back as falsy on if statements.
Changed the overview component to render at the top.

implemented image gallery default view

---

__tests__/Ratings.test.js
__tests__/ratingAverage.test.js
client/dist/index.html
client/dist/styles.css
client/src/components/App.jsx
client/src/components/Ratings.jsx
client/src/components/RatingsAndReviews/Review.jsx
client/src/components/util/ratingAverage.js
webpack.config.js

Hey guys,
Can you guys both review this? I finished up the 5 star ratings for it to dynamically render partial stars and it ended up being more complicated than I thought it would be so I want to make sure you guys are both on board with the current code as it'll end up in your own widgets too. 
Summary of changes: 
- Add a default object for product ratings for certain edge cases.
- Kept the same average algorithm 
- Create a new render function that will take the average rating and find out how much filled stars and empty stars to render. Then take the one star (if the rating is 0.25, 0.5, or 0.75, then render 40%, 50% or 60% of one star). I picked 40,50, 60 since it will render better on the screen.
Lets discuss when you guys get a chance. Thanks!

ks/starRender - Ratings - Ticket #14

---

client/dist/styles.css
client/src/components/App.jsx
client/src/components/Overview/ImageGallery.jsx
client/src/components/Overview/Overview.jsx
client/src/components/Overview/ProductInformation.jsx
client/src/components/Overview/StyleSelector.jsx
client/src/components/util/ratingAverage.js
webpack.config.js

-Added product information
-Implemented componentDidUpdate in Overview.jsx
-Commented out MomentLocalesPlugins() in webpack.config.js because it was not defined, even after npm installing moment. @ks10825n let me know how to get it to work, I ran npm install and npm run react-dev would not run because line 45 of webpack.config.js has an error.
-Removed the conditional rendering of the Overview component in App.jsx

Productinfo

---

client/dist/styles.css
client/src/components/Overview/ProductInformation.jsx

hey @kyelindholm @ks10825n 
- Added some styling to the product information

added some styling to product information

---

client/dist/styles.css
client/src/components/Overview/Overview.jsx
client/src/components/Overview/ProductDescription.jsx

hey @kyelindholm @ks10825n 
- Added Product Description, Slogan, and Features

implemented product description

---

client/src/components/Overview/Overview.jsx

@kyelindholm @ks10825n 
- Fixed 404 requests by removing componentDidMount

fixed 404 requests in overview.jsx

---

__tests__/QAComponents.test.js
client/src/components/QA/QuestionItem.jsx
client/src/components/QA/QuestionView.jsx

Hey! 
There will definitely be more tests to come, but I figured it'd be good to get some of the first ones merged with main to start.  Right now there are only two tests in this file, both testing the functionality of the QuestionList component. 
- Test 1 ensures that an amount of QuestionItems appropriate to the length of the questions array are being rendered within QuestionList
- Test 2 checks to make sure that the answerLimit prop correctly controls the number of answers that can be rendered (within each QuestionItem which itself is within QuestionList)
The changes to the components themselves are just added classNames to make tracking their rendering easier within the tests.

Started Q&A Components Enzyme Test File

---

client/dist/styles.css
client/src/components/QA/AddQuestion.jsx
client/src/components/QA/QuestionItem.jsx
client/src/components/QA/QuestionList.jsx
client/src/components/QA/QuestionSearch.jsx
client/src/components/QA/QuestionView.jsx

Hey guys,
Just did a quick pass of CSS to make the transition from our ProductView component feel a little more contiguous - there is no added or changed functionality in this PR (also refactored some inline CSS I previously had).

Light Styling

---

client/dist/styles.css
client/src/components/QA/AddQuestion.jsx
client/src/components/QA/QuestionList.jsx
client/src/components/QA/QuestionView.jsx

Again no functionality change, but I refactored the AddQuestion form into a modal window. When you click the "Add Question" button, the form will pop up in the middle of the screen (same form content as before). This popup will close upon clicking the submit button, or the 'x' in the upper right hand corner.

More styling!

---

client/src/components/Overview/AddToCart.jsx
client/src/components/Overview/Overview.jsx

hey @kyelindholm @ks10825n 
- Added dropdown menus for size and quantity

addtocart WIP

---

client/dist/styles.css
client/src/components/Ratings.jsx
client/src/components/RatingsAndReviews/RatingBreakdown.jsx
client/src/components/RatingsAndReviews/RatingsAndReviews.jsx
client/src/components/RatingsAndReviews/Review.jsx
client/src/components/RatingsAndReviews/ReviewList.jsx

Hey guys, this just renders the rating in a barchart format for the rating breakdown. I added some additional styling.
I added some styling on the body so it may or may not affect how it renders on your screen. It's mostly setting a max-width so everything renders properly, hopefully vertically aligned.
Otherwise, in regards to the rating breakdown, I'm only missing the filter toggle that I'll tackle once I get the product breakdown, and new review modal up and running.
Thanks!

ks/rr-v4-ratingbreakdown - Rating Breakdown - Ticket #21

---

client/dist/styles.css
client/src/components/Ratings.jsx
client/src/components/RatingsAndReviews/ProductBreakdown.jsx
client/src/components/RatingsAndReviews/RatingBreakdown.jsx
client/src/components/RatingsAndReviews/RatingsAndReviews.jsx
client/src/components/RatingsAndReviews/Review.jsx
client/src/components/RatingsAndReviews/ReviewList.jsx

This is to render the breakdown of the product. Rendering just the quality and comfort as any more I feel like it'll clutter.
This is a branch off of the rating breakdown, so all changes there will be here.
Not much else going on here!

ks/rr-v4-productbreakdown - Product Breakdown - Ticket #27

---

client/dist/styles.css
client/src/components/QA/QuestionItem.jsx
client/src/components/QA/QuestionList.jsx

Hey!
Answer now renders additional details (like the name of the author of each answer along with the time each answer was posted). Additionally I added spans within each QuestionItem and associated Answer that i'll write click functions for tthat will increment helpfulness - these spans currently display the helpfulness that each question/answer already has. I'm also now rendering the QuestionList and each QuestionItem's answers according to their helpfulness (from most helpful to least), as per Business Requirements.

QuestionItem Details

---

__tests__/App.test.js
__tests__/RatingsAndReviews.test.js
__tests__/ReviewList.test.js
__tests__/sampleData.js
client/src/components/RatingsAndReviews/RatingsAndReviews.jsx
client/src/components/RatingsAndReviews/ReviewList.jsx
package.json

Create tests for the Review List component. Left the sort and filter open-ended. Need to discuss with team or TM what best practice in testing functionality outside of unit

ks/rr-enzyme-v3 - Review List - Ticket #58

---

client/dist/styles.css
client/src/components/App.jsx
client/src/components/RatingsAndReviews/NewReview.jsx
client/src/components/RatingsAndReviews/ProductBreakdown.jsx
client/src/components/RatingsAndReviews/RatingsAndReviews.jsx
client/src/components/RatingsAndReviews/ReviewList.jsx

This was pretty hefty. I got everything to conditionally render correctly. I am getting stuck  on the API post request. Can you guys look and help me if my data structure is wrong? I'm getting a 422 error so I think it has to do with the body parameters.
Thanks!

ks/rr-v4-newReview - New Review - Ticket #28

---

client/dist/index.html
package-lock.json
package.json

@kyelindholm @ks10825n 
- Updated react to version 17 to be compatible with fontawesome

updated react to version 17

---

client/src/components/QA/QuestionItem.jsx
client/src/components/QA/QuestionList.jsx
client/src/components/QA/QuestionView.jsx

Now when you click on 'Report' in an answer, the text will change from 'Report' to 'Reported', it'll no longer be clickable, and the next time the QuestionList is rendered that answer won't show up.

answers can now be reported

---

client/dist/styles.css
client/src/components/RatingsAndReviews/NewReview.jsx
client/src/components/RatingsAndReviews/RatingsAndReviews.jsx
client/src/components/RatingsAndReviews/ReviewList.jsx

Figured out the correct syntax for the Review post request. There are actually some hidden criteria's on server-side that will reject the data. Such as if the body was underneath a certain amount of characters and the email needed to be appended with '@blah.com (or could be various .com/.org, haven't checked).

ks/rr v5 new review post - New Review Post Request - Ticket #28

---

client/dist/styles.css
client/src/components/Overview/Overview.jsx
client/src/components/Overview/Share.jsx

- Implemented social media share buttons

implemented social media share buttons

---

client/dist/styles.css
client/src/components/Overview/ImageGallery.jsx

- Implemented expanded image gallery

implemented expanded gallery

---

client/dist/styles.css
client/src/components/RatingsAndReviews/NewReview.jsx
client/src/components/RatingsAndReviews/RatingBreakdown.jsx
client/src/components/RatingsAndReviews/RatingsAndReviews.jsx
client/src/components/RatingsAndReviews/Review.jsx
client/src/components/RatingsAndReviews/ReviewList.jsx

Sorry for the late night PR. This PR is to implement the filter the review list by the rating, within the rating breakout on the left. The features wanted it to be able to toggle the rating as well, so I made them bold on toggle.
The only bugs I'm seeing right now overall, is that the review list will make an invalid GET request for pictures if the data coming back from the API is unrealiable (not a url). Also, I need to put in certain limitations within add review and add mandatory fields.

ks/rr v5 filter review list - Filtering the Review List - Ticket # 70

---

client/dist/styles.css
client/src/components/QA/QuestionList.jsx
client/src/components/QA/QuestionView.jsx

Mostly just yoinked Kevin's button style to make the page more consistent looking. The background color/cursor also now changes when hovered to indicate clickability.

Styled Questions Button

---

client/dist/styles.css
client/src/components/QA/QuestionItem.jsx

Super simple implementation - just mapping through the photos array element of each question within the QuestionItem.

Render answer pictures

---

client/dist/styles.css
client/src/components/Overview/ImageGallery.jsx

- Implemented image carousel for the thumbnail pictures
- Will fix css conflicts

Thumbnailcarousel

---

client/src/components/Overview/ImageGallery.jsx

@kyelindholm @ks10825n 
- Missed a curly bracket when resolving a conflict in image gallery.

fixed missing curly bracket

---

client/dist/styles.css
client/src/components/QA/AddAnswer.jsx
client/src/components/QA/AddQuestion.jsx

Hey y'all,
As the title implies, just made my modals (Add Question & Add Answer) look a little different. Changed the background color and added some style to the submit button to make it consistent with our other buttons' styles.

light modal style rework

---

client/dist/styles.css
client/src/components/App.jsx
client/src/components/Overview/AddToCart.jsx
client/src/components/Overview/ImageGallery.jsx
client/src/components/Overview/Overview.jsx
client/src/components/Overview/ProductInformation.jsx
client/src/components/Overview/StyleSelector.jsx

- Added Styling
- Added sale price when style is on sale
- Added link to "Read all reviews"
- Fixed Add To Cart size and quantity default values, and reset quantity when changing size

styling and techdebt

---

package-lock.json
package.json
webpack.config.js

Hey this is a fix for a webpack config around Moment. This should make the bundle size smaller

fix webpack config to require us-only moment

---

package.json
webpack.config.js

@ks10825n @kyelindholm 
- Added production mode for webpack

Webpackconfig

---

client/dist/styles.css
client/src/components/Overview/ImageGallery.jsx
client/src/components/Overview/ProductInformation.jsx

@ks10825n @kyelindholm 
- Final styling before deploying

final styling
